---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: proxmox_template
      vars:
        proxmox_template_qm: /usr/local/bin/qm
        proxmox_template_image_url: http://127.0.0.1:8080/noble-server-cloudimg-amd64.img
        proxmox_template_image_checksum: sha256:http://127.0.0.1:8080/SHA256SUMS
        proxmox_template_storage: local-zfs
        proxmox_template_bridge: vmbr1
